#!/usr/bin/env ruby
# This script is based on one created at solowizard.com
# http://github.com/tommyh/solo_wizard
# (c) 2012, Tom Hallett
# This script may be freely distributed under the MIT license.
require 'fileutils'

def cmd_ok?(cmd)
  `#{cmd} 2>&1 >/dev/null`
  return $?.exitstatus == 0
end

def git_pull(dir)
  Dir.chdir(dir)
  system "git pull"
ensure
  Dir.chdir("..")
end

unless cmd_ok?("which soloist")
  if cmd_ok?("rvm --version")
    system "gem install soloist"
  else
    system "sudo gem install soloist"
  end
end

cookbooks_dir = File.expand_path("cookbooks", "~")
FileUtils.mkdir_p(cookbooks_dir)
Dir.chdir(cookbooks_dir)

["https://github.com/pivotal/pivotal_workstation.git",
 "https://github.com/opscode-cookbooks/dmg.git",
 "https://github.com/kitchenplan/chef-osxdefaults.git",
 "https://github.com/SealedEnvelope/se-dev-box.git"].each do |cookbook|
  cookbook_dir = File.basename(cookbook, ".git")
  cookbook_dir = "osxdefaults" if cookbook_dir == "chef-osxdefaults"
  if File.directory?(cookbook_dir)
    git_pull(cookbook_dir)
  else
    system "git clone #{cookbook} #{cookbook_dir}"
  end
end

if File.exists?("soloistrc")
  system "soloist"
else
  puts "You need a ~/cookbooks/soloistrc file - see se-dev-box/generate_soloistrc"
end
